bernoulli: tests_bernoulli.cpp
	g++ tests_bernoulli.cpp	hamming_binaire.cpp hamming_f16.cpp -o bernoulli && ./bernoulli

markov: hamming_f16.cpp
	g++ tests_markov.cpp hamming_binaire.cpp hamming_f16.cpp -o markov && ./markov